CREATE DATABASE IF NOT EXISTS krest_center_db
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE krest_center_db;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(190) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  phone VARCHAR(30) NULL,
  role ENUM('ADMIN','SELLER','BUYER') NOT NULL,
  status ENUM('ACTIVE','INACTIVE','SUSPENDED') NOT NULL DEFAULT 'ACTIVE',
  profile_image VARCHAR(500) NULL,
  cover_image VARCHAR(500) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS admin_login_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  admin_id BIGINT UNSIGNED NOT NULL,
  login_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip_address VARCHAR(64) NULL,
  CONSTRAINT fk_admin_log_user FOREIGN KEY (admin_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS center_requests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  seller_id BIGINT UNSIGNED NOT NULL,
  center_name VARCHAR(150) NOT NULL,
  category VARCHAR(100) NOT NULL,
  description TEXT NULL,
  location VARCHAR(255) NULL,
  business_info TEXT NULL,
  status ENUM('PENDING','APPROVED','REJECTED') NOT NULL DEFAULT 'PENDING',
  admin_note TEXT NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  reviewed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_center_req_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_center_req_admin FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS centers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  seller_id BIGINT UNSIGNED NOT NULL,
  source_request_id BIGINT UNSIGNED NULL UNIQUE,
  name VARCHAR(150) NOT NULL,
  category VARCHAR(100) NOT NULL,
  description TEXT NULL,
  location VARCHAR(255) NULL,
  profile_image VARCHAR(500) NULL,
  cover_image VARCHAR(500) NULL,
  rating DECIMAL(3,2) NOT NULL DEFAULT 0,
  status ENUM('ACTIVE','WARNING','SUSPENDED','CLOSED') NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_center_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_center_request FOREIGN KEY (source_request_id) REFERENCES center_requests(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS reports (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  buyer_id BIGINT UNSIGNED NOT NULL,
  target_type ENUM('CENTER','SELLER','PRODUCT') NOT NULL,
  target_id BIGINT UNSIGNED NOT NULL,
  reason VARCHAR(120) NOT NULL,
  details TEXT NULL,
  evidence_url VARCHAR(500) NULL,
  status ENUM('OPEN','INVESTIGATING','RESOLVED','REJECTED') NOT NULL DEFAULT 'OPEN',
  admin_note TEXT NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_report_buyer FOREIGN KEY (buyer_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_report_admin FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS center_warnings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  center_id BIGINT UNSIGNED NOT NULL,
  issued_by BIGINT UNSIGNED NOT NULL,
  reason VARCHAR(255) NOT NULL,
  details TEXT NULL,
  level TINYINT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('OPEN','ACKNOWLEDGED','RESOLVED') NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_warning_center FOREIGN KEY (center_id) REFERENCES centers(id) ON DELETE CASCADE,
  CONSTRAINT fk_warning_admin FOREIGN KEY (issued_by) REFERENCES users(id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS seller_admin_agreements (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  seller_id BIGINT UNSIGNED NOT NULL,
  center_id BIGINT UNSIGNED NULL,
  commission_rate DECIMAL(5,2) NOT NULL,
  terms TEXT NULL,
  status ENUM('DRAFT','ACTIVE','ENDED') NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_agreement_seller FOREIGN KEY (seller_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_agreement_center FOREIGN KEY (center_id) REFERENCES centers(id) ON DELETE SET NULL
);

CREATE INDEX idx_center_requests_status ON center_requests(status);
CREATE INDEX idx_centers_status ON centers(status);
CREATE INDEX idx_reports_status ON reports(status);


-- PART 2 SELLER TABLES


CREATE TABLE IF NOT EXISTS products(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,center_id BIGINT UNSIGNED NOT NULL,name VARCHAR(180) NOT NULL,category VARCHAR(100) NOT NULL,sku VARCHAR(100) NULL,description TEXT NULL,price DECIMAL(12,2) NOT NULL DEFAULT 0,stock INT UNSIGNED NOT NULL DEFAULT 0,image_url VARCHAR(500) NULL,view_count BIGINT UNSIGNED NOT NULL DEFAULT 0,status ENUM('DRAFT','ACTIVE','HIDDEN','OUT_OF_STOCK','DELETED') NOT NULL DEFAULT 'DRAFT',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_products_center FOREIGN KEY(center_id) REFERENCES centers(id) ON DELETE CASCADE,UNIQUE KEY uk_center_sku(center_id,sku),INDEX idx_products_center_status(center_id,status));
CREATE TABLE IF NOT EXISTS product_variants(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id BIGINT UNSIGNED NOT NULL,color VARCHAR(80) NULL,size VARCHAR(50) NULL,weight_value DECIMAL(10,2) NULL,weight_unit ENUM('g','kg') NULL,volume_value DECIMAL(10,2) NULL,volume_unit ENUM('ml','L') NULL,variant_price DECIMAL(12,2) NULL,stock INT UNSIGNED NOT NULL DEFAULT 0,sku VARCHAR(100) NULL,status ENUM('ACTIVE','OUT_OF_STOCK','DISABLED') NOT NULL DEFAULT 'ACTIVE',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_product_variants_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,UNIQUE KEY uk_product_variant_sku(product_id,sku),INDEX idx_product_variants_product_status(product_id,status));
CREATE TABLE IF NOT EXISTS product_images(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,product_id BIGINT UNSIGNED NOT NULL,image_url VARCHAR(500) NOT NULL,is_primary BOOLEAN NOT NULL DEFAULT FALSE,sort_order INT NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_product_images_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS orders(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,buyer_id BIGINT UNSIGNED NOT NULL,center_id BIGINT UNSIGNED NOT NULL,total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,status ENUM('PENDING','CONFIRMED','PREPARING','SHIPPED','DELIVERED','CANCELLED') NOT NULL DEFAULT 'PENDING',delivery_address VARCHAR(500) NULL,payment_status ENUM('PENDING','PAID','FAILED','REFUNDED') NOT NULL DEFAULT 'PENDING',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_orders_buyer FOREIGN KEY(buyer_id) REFERENCES users(id) ON DELETE RESTRICT,CONSTRAINT fk_orders_center FOREIGN KEY(center_id) REFERENCES centers(id) ON DELETE RESTRICT,INDEX idx_orders_center_status(center_id,status));
CREATE TABLE IF NOT EXISTS order_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,variant_id BIGINT UNSIGNED NULL,selected_color VARCHAR(80) NULL,selected_size VARCHAR(50) NULL,selected_weight_value DECIMAL(10,2) NULL,selected_weight_unit VARCHAR(10) NULL,selected_volume_value DECIMAL(10,2) NULL,selected_volume_unit VARCHAR(10) NULL,variant_sku VARCHAR(100) NULL,quantity INT UNSIGNED NOT NULL,unit_price DECIMAL(12,2) NOT NULL,CONSTRAINT fk_order_items_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,CONSTRAINT fk_order_items_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE RESTRICT,CONSTRAINT fk_order_items_variant FOREIGN KEY(variant_id) REFERENCES product_variants(id) ON DELETE SET NULL,INDEX idx_order_items_variant(variant_id));
CREATE TABLE IF NOT EXISTS product_reviews(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,buyer_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,rating TINYINT UNSIGNED NOT NULL,comment TEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_product_review_buyer FOREIGN KEY(buyer_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_product_review_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,CONSTRAINT chk_product_rating CHECK(rating BETWEEN 1 AND 5),UNIQUE KEY uk_product_review_once(buyer_id,product_id));
CREATE TABLE IF NOT EXISTS center_reviews(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,buyer_id BIGINT UNSIGNED NOT NULL,center_id BIGINT UNSIGNED NOT NULL,rating TINYINT UNSIGNED NOT NULL,comment TEXT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_center_review_buyer FOREIGN KEY(buyer_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_center_review_center FOREIGN KEY(center_id) REFERENCES centers(id) ON DELETE CASCADE,CONSTRAINT chk_center_rating CHECK(rating BETWEEN 1 AND 5),UNIQUE KEY uk_center_review_once(buyer_id,center_id));
CREATE TABLE IF NOT EXISTS notifications(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,title VARCHAR(180) NOT NULL,message TEXT NOT NULL,type VARCHAR(50) NOT NULL DEFAULT 'INFO',is_read BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_notifications_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,INDEX idx_notifications_user(user_id,is_read,created_at));


-- PART 3 BUYER TABLES

CREATE TABLE IF NOT EXISTS buyer_profiles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL UNIQUE,bio TEXT NULL,default_address VARCHAR(500) NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_buyer_profile_user FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS carts(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,buyer_id BIGINT UNSIGNED NOT NULL UNIQUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_cart_buyer FOREIGN KEY(buyer_id) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS cart_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,cart_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,variant_id BIGINT UNSIGNED NULL,quantity INT UNSIGNED NOT NULL DEFAULT 1,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_cart_item_cart FOREIGN KEY(cart_id) REFERENCES carts(id) ON DELETE CASCADE,CONSTRAINT fk_cart_item_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,CONSTRAINT fk_cart_items_variant FOREIGN KEY(variant_id) REFERENCES product_variants(id) ON DELETE CASCADE,INDEX idx_cart_items_cart(cart_id),INDEX idx_cart_items_variant(variant_id),INDEX idx_cart_product_variant(cart_id,product_id,variant_id));
CREATE TABLE IF NOT EXISTS wishlist_items(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,buyer_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_wishlist_buyer FOREIGN KEY(buyer_id) REFERENCES users(id) ON DELETE CASCADE,CONSTRAINT fk_wishlist_product FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,UNIQUE KEY uk_wishlist_product(buyer_id,product_id));
CREATE TABLE IF NOT EXISTS order_checkout_details(order_id BIGINT UNSIGNED PRIMARY KEY,delivery_phone VARCHAR(30) NULL,payment_method ENUM('COD','KBZPAY_DEMO','WAVEPAY_DEMO') NOT NULL DEFAULT 'COD',CONSTRAINT fk_checkout_order FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE);

-- FINAL AUTH INTEGRATION
CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_password_reset_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_password_reset_user (user_id, used_at, expires_at)
);
