const db=require("../../config/db");

async function notify(userId,title,message,type="ADMIN_ACTION",conn=db){
  await conn.query("INSERT INTO notifications(user_id,title,message,type) VALUES(?,?,?,?)",[userId,title,message,type]);
}

exports.me=async(req,res,next)=>{try{const [rows]=await db.query("SELECT id,name,email,phone,role,status,profile_image,cover_image FROM users WHERE id=? AND role='ADMIN' LIMIT 1",[req.user.id]);if(!rows.length)return res.status(404).json({success:false,message:"Admin account not found"});res.json({success:true,user:rows[0]})}catch(e){next(e)}};

exports.dashboard=async(req,res,next)=>{try{const [[pending]]=await db.query("SELECT COUNT(*) count FROM center_requests WHERE status='PENDING'");const [[centers]]=await db.query("SELECT COUNT(*) count FROM centers WHERE status IN ('ACTIVE','WARNING')");const [[buyers]]=await db.query("SELECT COUNT(*) count FROM users WHERE role='BUYER' AND status='ACTIVE'");const [[reports]]=await db.query("SELECT COUNT(*) count FROM reports WHERE status IN ('OPEN','INVESTIGATING')");const [latestRequests]=await db.query(`SELECT cr.id,cr.center_name,cr.status,cr.created_at,u.name seller_name FROM center_requests cr JOIN users u ON u.id=cr.seller_id ORDER BY cr.created_at DESC LIMIT 6`);res.json({success:true,stats:{pendingCenterRequests:pending.count,activeCenters:centers.count,buyers:buyers.count,openReports:reports.count},latestRequests})}catch(e){next(e)}};

exports.centers=async(req,res,next)=>{try{const [rows]=await db.query(`SELECT c.id,c.name,c.category,c.location,c.status,c.rating,c.created_at,u.id seller_id,u.name seller_name,u.email seller_email,COUNT(DISTINCT p.id) product_count,COUNT(DISTINCT w.id) warning_count FROM centers c JOIN users u ON u.id=c.seller_id LEFT JOIN products p ON p.center_id=c.id AND p.status<>'DELETED' LEFT JOIN center_warnings w ON w.center_id=c.id AND w.status='OPEN' GROUP BY c.id ORDER BY FIELD(c.status,'WARNING','ACTIVE','SUSPENDED','CLOSED'),c.created_at DESC`);res.json({success:true,centers:rows})}catch(e){next(e)}};
exports.center=async(req,res,next)=>{try{const [rows]=await db.query(`SELECT c.*,u.name seller_name,u.email seller_email,u.phone seller_phone,(SELECT COUNT(*) FROM products p WHERE p.center_id=c.id AND p.status<>'DELETED') product_count,(SELECT COUNT(*) FROM orders o WHERE o.center_id=c.id) order_count FROM centers c JOIN users u ON u.id=c.seller_id WHERE c.id=? LIMIT 1`,[req.params.id]);if(!rows.length)return res.status(404).json({success:false,message:"Center not found"});const [warnings]=await db.query("SELECT w.*,a.name admin_name FROM center_warnings w JOIN users a ON a.id=w.issued_by WHERE w.center_id=? ORDER BY w.created_at DESC LIMIT 20",[req.params.id]);res.json({success:true,center:rows[0],warnings})}catch(e){next(e)}};
exports.updateCenterStatus=async(req,res,next)=>{try{const allowed=['ACTIVE','WARNING','SUSPENDED','CLOSED'],status=req.body.status;if(!allowed.includes(status))return res.status(400).json({success:false,message:"Invalid center status"});const [rows]=await db.query("SELECT c.id,c.name,c.seller_id FROM centers c WHERE c.id=?",[req.params.id]);if(!rows.length)return res.status(404).json({success:false,message:"Center not found"});await db.query("UPDATE centers SET status=? WHERE id=?",[status,req.params.id]);await notify(rows[0].seller_id,"Center status updated",`${rows[0].name} is now ${status}.`,"CENTER_STATUS");res.json({success:true,message:"Center status updated"})}catch(e){next(e)}};
exports.addWarning=async(req,res,next)=>{try{const reason=String(req.body.reason||'').trim(),details=String(req.body.details||'').trim(),level=Math.min(3,Math.max(1,Number(req.body.level||1)));if(!reason)return res.status(400).json({success:false,message:"Warning reason is required"});const [rows]=await db.query("SELECT id,name,seller_id,status FROM centers WHERE id=?",[req.params.id]);if(!rows.length)return res.status(404).json({success:false,message:"Center not found"});await db.query("INSERT INTO center_warnings(center_id,issued_by,reason,details,level,status) VALUES(?,?,?,?,?,'OPEN')",[req.params.id,req.user.id,reason,details||null,level]);if(rows[0].status==='ACTIVE')await db.query("UPDATE centers SET status='WARNING' WHERE id=?",[req.params.id]);await notify(rows[0].seller_id,"Center warning issued",`${rows[0].name}: ${reason}`,"CENTER_WARNING");res.status(201).json({success:true,message:"Warning issued"})}catch(e){next(e)}};

exports.sellers=async(req,res,next)=>{try{const [rows]=await db.query(`SELECT u.id,u.name,u.email,u.phone,u.status,u.created_at,c.id center_id,c.name center_name,c.status center_status,COUNT(DISTINCT p.id) product_count FROM users u LEFT JOIN centers c ON c.seller_id=u.id AND c.id=(SELECT MAX(c2.id) FROM centers c2 WHERE c2.seller_id=u.id) LEFT JOIN products p ON p.center_id=c.id AND p.status<>'DELETED' WHERE u.role='SELLER' GROUP BY u.id,c.id ORDER BY u.created_at DESC`);res.json({success:true,sellers:rows})}catch(e){next(e)}};
exports.buyers=async(req,res,next)=>{try{const [rows]=await db.query(`SELECT u.id,u.name,u.email,u.phone,u.status,u.created_at,COUNT(DISTINCT o.id) order_count,COUNT(DISTINCT r.id) report_count FROM users u LEFT JOIN orders o ON o.buyer_id=u.id LEFT JOIN reports r ON r.buyer_id=u.id WHERE u.role='BUYER' GROUP BY u.id ORDER BY u.created_at DESC`);res.json({success:true,buyers:rows})}catch(e){next(e)}};
exports.products=async(req,res,next)=>{try{const [rows]=await db.query(`SELECT p.id,p.name,p.category,p.price,p.stock,p.status,p.created_at,c.name center_name,u.name seller_name FROM products p JOIN centers c ON c.id=p.center_id JOIN users u ON u.id=c.seller_id WHERE p.status<>'DELETED' ORDER BY p.created_at DESC`);res.json({success:true,products:rows})}catch(e){next(e)}};
exports.updateProductStatus=async(req,res,next)=>{try{const allowed=['ACTIVE','HIDDEN','DELETED'],requested=req.body.status;if(!allowed.includes(requested))return res.status(400).json({success:false,message:"Invalid product status"});const [rows]=await db.query(`SELECT p.id,p.name,p.stock,c.seller_id FROM products p JOIN centers c ON c.id=p.center_id WHERE p.id=? AND p.status<>'DELETED'`,[req.params.id]);if(!rows.length)return res.status(404).json({success:false,message:"Product not found"});const finalStatus=requested==='ACTIVE'&&Number(rows[0].stock)===0?'OUT_OF_STOCK':requested;await db.query("UPDATE products SET status=? WHERE id=?",[finalStatus,req.params.id]);await notify(rows[0].seller_id,"Product moderation update",`${rows[0].name} is now ${finalStatus}.`,"PRODUCT_MODERATION");res.json({success:true,message:"Product status updated",status:finalStatus})}catch(e){next(e)}};

exports.warnings=async(req,res,next)=>{try{const [rows]=await db.query(`SELECT w.*,c.name center_name,u.name admin_name FROM center_warnings w JOIN centers c ON c.id=w.center_id JOIN users u ON u.id=w.issued_by ORDER BY FIELD(w.status,'OPEN','ACKNOWLEDGED','RESOLVED'),w.created_at DESC`);res.json({success:true,warnings:rows})}catch(e){next(e)}};
exports.updateWarning=async(req,res,next)=>{try{const allowed=['OPEN','ACKNOWLEDGED','RESOLVED'];if(!allowed.includes(req.body.status))return res.status(400).json({success:false,message:"Invalid warning status"});await db.query("UPDATE center_warnings SET status=? WHERE id=?",[req.body.status,req.params.id]);res.json({success:true})}catch(e){next(e)}};

exports.finance=async(req,res,next)=>{try{const [[sales]]=await db.query("SELECT COALESCE(SUM(CASE WHEN status='DELIVERED' THEN total_amount ELSE 0 END),0) gross,COALESCE(SUM(CASE WHEN status IN ('PENDING','CONFIRMED','PREPARING','SHIPPED') THEN total_amount ELSE 0 END),0) pending FROM orders");const [[agreements]]=await db.query("SELECT COUNT(*) active FROM seller_admin_agreements WHERE status='ACTIVE'");const [delivered]=await db.query(`SELECT o.total_amount,COALESCE((SELECT sa.commission_rate FROM seller_admin_agreements sa WHERE sa.center_id=o.center_id AND sa.status='ACTIVE' ORDER BY sa.id DESC LIMIT 1),8) commission_rate FROM orders o WHERE o.status='DELIVERED'`);const commission=delivered.reduce((s,o)=>s+Number(o.total_amount)*Number(o.commission_rate)/100,0);res.json({success:true,summary:{grossMarketplaceValue:Number(sales.gross),platformCommission:commission,pendingSettlement:Number(sales.pending),activeAgreements:agreements.active}})}catch(e){next(e)}};
exports.agreements=async(req,res,next)=>{try{const [rows]=await db.query(`SELECT a.*,u.name seller_name,c.name center_name FROM seller_admin_agreements a JOIN users u ON u.id=a.seller_id LEFT JOIN centers c ON c.id=a.center_id ORDER BY a.created_at DESC`);res.json({success:true,agreements:rows})}catch(e){next(e)}};
exports.createAgreement=async(req,res,next)=>{const conn=await db.getConnection();try{const sellerId=Number(req.body.sellerId),centerId=req.body.centerId?Number(req.body.centerId):null,rate=Number(req.body.commissionRate),terms=String(req.body.terms||'').trim(),status=req.body.status||'DRAFT';if(!sellerId||!Number.isFinite(rate)||rate<0||rate>100||!['DRAFT','ACTIVE','ENDED'].includes(status))return res.status(400).json({success:false,message:"Seller, 0-100 commission rate and valid status are required"});const [seller]=await conn.query("SELECT id FROM users WHERE id=? AND role='SELLER'",[sellerId]);if(!seller.length)return res.status(404).json({success:false,message:"Seller not found"});if(centerId){const [center]=await conn.query("SELECT id FROM centers WHERE id=? AND seller_id=?",[centerId,sellerId]);if(!center.length)return res.status(400).json({success:false,message:"Center does not belong to seller"})}await conn.beginTransaction();if(status==='ACTIVE'&&centerId)await conn.query("UPDATE seller_admin_agreements SET status='ENDED' WHERE center_id=? AND status='ACTIVE'",[centerId]);const [r]=await conn.query("INSERT INTO seller_admin_agreements(seller_id,center_id,commission_rate,terms,status) VALUES(?,?,?,?,?)",[sellerId,centerId,rate,terms||null,status]);await notify(sellerId,"Seller agreement updated",`A ${rate}% commission agreement is ${status.toLowerCase()}.`,"AGREEMENT",conn);await conn.commit();res.status(201).json({success:true,agreementId:r.insertId})}catch(e){await conn.rollback();next(e)}finally{conn.release()}};

exports.notifications=async(req,res,next)=>{try{const [rows]=await db.query("SELECT * FROM notifications WHERE user_id=? ORDER BY created_at DESC LIMIT 50",[req.user.id]);res.json({success:true,notifications:rows})}catch(e){next(e)}};
exports.readNotifications=async(req,res,next)=>{try{await db.query("UPDATE notifications SET is_read=TRUE WHERE user_id=?",[req.user.id]);res.json({success:true})}catch(e){next(e)}};
